#define  FREQ1_DERATEEN             DERATEEN_FREQ1     
#define  FREQ1_DERATEINT            DERATEINT_FREQ1    
#define  FREQ1_PWRTMG               PWRTMG_FREQ1       
#define  FREQ1_RFSHCTL0             RFSHCTL0_FREQ1 
#define  FREQ1_RFSHTMG              RFSHTMG_FREQ1      
#define  FREQ1_RFSHTMG1             RFSHTMG1_FREQ1     
#define  FREQ1_INIT3                INIT3_FREQ1        
#define  FREQ1_INIT4                INIT4_FREQ1        
#define  FREQ1_INIT6                INIT6_FREQ1        
#define  FREQ1_INIT7                INIT7_FREQ1        
#define  FREQ1_RANKCTL              RANKCTL_FREQ1      
#define  FREQ1_RANKCTL1             RANKCTL1_FREQ1     
#define  FREQ1_DRAMTMG0             DRAMTMG0_FREQ1     
#define  FREQ1_DRAMTMG1             DRAMTMG1_FREQ1     
#define  FREQ1_DRAMTMG2             DRAMTMG2_FREQ1     
#define  FREQ1_DRAMTMG3             DRAMTMG3_FREQ1     
#define  FREQ1_DRAMTMG4             DRAMTMG4_FREQ1     
#define  FREQ1_DRAMTMG5             DRAMTMG5_FREQ1     
#define  FREQ1_DRAMTMG6             DRAMTMG6_FREQ1     
#define  FREQ1_DRAMTMG7             DRAMTMG7_FREQ1     
#define  FREQ1_DRAMTMG8             DRAMTMG8_FREQ1     
#define  FREQ1_DRAMTMG12            DRAMTMG12_FREQ1 
#define  FREQ1_DRAMTMG13            DRAMTMG13_FREQ1
#define  FREQ1_DRAMTMG14            DRAMTMG14_FREQ1
#define  FREQ1_ZQCTL0               ZQCTL0_FREQ1  
#define  FREQ1_DFITMG0              DFITMG0_FREQ1
#define  FREQ1_DFITMG1              DFITMG1_FREQ1
#define  FREQ1_DFITMG2              DFITMG2_FREQ1
#define  FREQ1_ODTCFG               ODTCFG_FREQ1 

#define FREQ1_DERATEEN                             DERATEEN_FREQ1                                
#define FREQ1_DERATEINT                            DERATEINT_FREQ1                               
#define FREQ1_PWRTMG                               PWRTMG_FREQ1                                  
#define FREQ1_HWFFCEX_RANK1                        HWFFCEX_RANK1_FREQ1                           
#define FREQ1_RFSHCTL0                             RFSHCTL0_FREQ1                                
#define FREQ1_RFSHTMG                              RFSHTMG_FREQ1                                 
#define FREQ1_RFSHTMG1                             RFSHTMG1_FREQ1                                
#define FREQ1_INIT3                                INIT3_FREQ1                                   
#define FREQ1_INIT4                                INIT4_FREQ1                                   
#define FREQ1_INIT6                                INIT6_FREQ1                                   
#define FREQ1_INIT7                                INIT7_FREQ1                                   
#define FREQ1_RANKCTL                              RANKCTL_FREQ1                                 
#define FREQ1_RANKCTL1                             RANKCTL1_FREQ1                                
#define FREQ1_DRAMTMG0                             DRAMTMG0_FREQ1                                
#define FREQ1_DRAMTMG1                             DRAMTMG1_FREQ1                                
#define FREQ1_DRAMTMG2                             DRAMTMG2_FREQ1                                
#define FREQ1_DRAMTMG3                             DRAMTMG3_FREQ1                                
#define FREQ1_DRAMTMG4                             DRAMTMG4_FREQ1                                
#define FREQ1_DRAMTMG5                             DRAMTMG5_FREQ1                                
#define FREQ1_DRAMTMG6                             DRAMTMG6_FREQ1                                
#define FREQ1_DRAMTMG7                             DRAMTMG7_FREQ1                                
#define FREQ1_DRAMTMG8                             DRAMTMG8_FREQ1                                
#define FREQ1_DRAMTMG9                             DRAMTMG9_FREQ1                                
#define FREQ1_DRAMTMG11                            DRAMTMG11_FREQ1                               
#define FREQ1_DRAMTMG12                            DRAMTMG12_FREQ1                               
#define FREQ1_DRAMTMG13                            DRAMTMG13_FREQ1                               
#define FREQ1_DRAMTMG14                            DRAMTMG14_FREQ1                               
#define FREQ1_DRAMTMG15                            DRAMTMG15_FREQ1                               
#define FREQ1_DRAMTMG17                            DRAMTMG17_FREQ1                               
#define FREQ1_ZQCTL0                               ZQCTL0_FREQ1                                  
#define FREQ1_DFITMG0                              DFITMG0_FREQ1                                 
#define FREQ1_DFITMG1                              DFITMG1_FREQ1                                 
#define FREQ1_DFITMG2                              DFITMG2_FREQ1                                 
#define FREQ1_ODTCFG                               ODTCFG_FREQ1                                  
#define FREQ1_RCDINIT1                             RCDINIT1_FREQ1                                
#define FREQ1_RCDINIT2                             RCDINIT2_FREQ1                                
#define FREQ1_RCDINIT3                             RCDINIT3_FREQ1                                
#define FREQ1_RCDINIT4                             RCDINIT4_FREQ1                                
#define FREQ2_DERATEEN                             DERATEEN_FREQ2                                
#define FREQ2_DERATEINT                            DERATEINT_FREQ2                               
#define FREQ2_PWRTMG                               PWRTMG_FREQ2                                  
#define FREQ2_HWFFCEX_RANK1                        HWFFCEX_RANK1_FREQ2                           
#define FREQ2_RFSHCTL0                             RFSHCTL0_FREQ2                                
#define FREQ2_RFSHTMG                              RFSHTMG_FREQ2                                 
#define FREQ2_RFSHTMG1                             RFSHTMG1_FREQ2                                
#define FREQ2_INIT3                                INIT3_FREQ2                                   
#define FREQ2_INIT4                                INIT4_FREQ2                                   
#define FREQ2_INIT6                                INIT6_FREQ2                                   
#define FREQ2_INIT7                                INIT7_FREQ2                                   
#define FREQ2_RANKCTL                              RANKCTL_FREQ2                                 
#define FREQ2_RANKCTL1                             RANKCTL1_FREQ2                                
#define FREQ2_DRAMTMG0                             DRAMTMG0_FREQ2                                
#define FREQ2_DRAMTMG1                             DRAMTMG1_FREQ2                                
#define FREQ2_DRAMTMG2                             DRAMTMG2_FREQ2                                
#define FREQ2_DRAMTMG3                             DRAMTMG3_FREQ2                                
#define FREQ2_DRAMTMG4                             DRAMTMG4_FREQ2                                
#define FREQ2_DRAMTMG5                             DRAMTMG5_FREQ2                                
#define FREQ2_DRAMTMG6                             DRAMTMG6_FREQ2                                
#define FREQ2_DRAMTMG7                             DRAMTMG7_FREQ2                                
#define FREQ2_DRAMTMG8                             DRAMTMG8_FREQ2                                
#define FREQ2_DRAMTMG9                             DRAMTMG9_FREQ2                                
#define FREQ2_DRAMTMG11                            DRAMTMG11_FREQ2                               
#define FREQ2_DRAMTMG12                            DRAMTMG12_FREQ2                               
#define FREQ2_DRAMTMG13                            DRAMTMG13_FREQ2                               
#define FREQ2_DRAMTMG14                            DRAMTMG14_FREQ2                               
#define FREQ2_DRAMTMG15                            DRAMTMG15_FREQ2                               
#define FREQ2_DRAMTMG17                            DRAMTMG17_FREQ2                               
#define FREQ2_ZQCTL0                               ZQCTL0_FREQ2                                  
#define FREQ2_DFITMG0                              DFITMG0_FREQ2                                 
#define FREQ2_DFITMG1                              DFITMG1_FREQ2                                 
#define FREQ2_DFITMG2                              DFITMG2_FREQ2                                 
#define FREQ2_ODTCFG                               ODTCFG_FREQ2                                  
#define FREQ2_RCDINIT1                             RCDINIT1_FREQ2                                
#define FREQ2_RCDINIT2                             RCDINIT2_FREQ2                                
#define FREQ2_RCDINIT3                             RCDINIT3_FREQ2                                
#define FREQ2_RCDINIT4                             RCDINIT4_FREQ2                                
#define FREQ3_DERATEEN                             DERATEEN_FREQ3                                
#define FREQ3_DERATEINT                            DERATEINT_FREQ3                               
#define FREQ3_PWRTMG                               PWRTMG_FREQ3                                  
#define FREQ3_HWFFCEX_RANK1                        HWFFCEX_RANK1_FREQ3                           
#define FREQ3_RFSHCTL0                             RFSHCTL0_FREQ3                                
#define FREQ3_RFSHTMG                              RFSHTMG_FREQ3                                 
#define FREQ3_RFSHTMG1                             RFSHTMG1_FREQ3                                
#define FREQ3_INIT3                                INIT3_FREQ3                                   
#define FREQ3_INIT4                                INIT4_FREQ3                                   
#define FREQ3_INIT6                                INIT6_FREQ3                                   
#define FREQ3_INIT7                                INIT7_FREQ3                                   
#define FREQ3_RANKCTL                              RANKCTL_FREQ3                                 
#define FREQ3_RANKCTL1                             RANKCTL1_FREQ3                                
#define FREQ3_DRAMTMG0                             DRAMTMG0_FREQ3                                
#define FREQ3_DRAMTMG1                             DRAMTMG1_FREQ3                                
#define FREQ3_DRAMTMG2                             DRAMTMG2_FREQ3                                
#define FREQ3_DRAMTMG3                             DRAMTMG3_FREQ3                                
#define FREQ3_DRAMTMG4                             DRAMTMG4_FREQ3                                
#define FREQ3_DRAMTMG5                             DRAMTMG5_FREQ3                                
#define FREQ3_DRAMTMG6                             DRAMTMG6_FREQ3                                
#define FREQ3_DRAMTMG7                             DRAMTMG7_FREQ3                                
#define FREQ3_DRAMTMG8                             DRAMTMG8_FREQ3                                
#define FREQ3_DRAMTMG9                             DRAMTMG9_FREQ3                                
#define FREQ3_DRAMTMG11                            DRAMTMG11_FREQ3                               
#define FREQ3_DRAMTMG12                            DRAMTMG12_FREQ3                               
#define FREQ3_DRAMTMG13                            DRAMTMG13_FREQ3                               
#define FREQ3_DRAMTMG14                            DRAMTMG14_FREQ3                               
#define FREQ3_DRAMTMG15                            DRAMTMG15_FREQ3                               
#define FREQ3_DRAMTMG17                            DRAMTMG17_FREQ3                               
#define FREQ3_ZQCTL0                               ZQCTL0_FREQ3                                  
#define FREQ3_DFITMG0                              DFITMG0_FREQ3                                 
#define FREQ3_DFITMG1                              DFITMG1_FREQ3                                 
#define FREQ3_DFITMG2                              DFITMG2_FREQ3                                 
#define FREQ3_ODTCFG                               ODTCFG_FREQ3                                  
#define FREQ3_RCDINIT1                             RCDINIT1_FREQ3                                
#define FREQ3_RCDINIT2                             RCDINIT2_FREQ3                                
#define FREQ3_RCDINIT3                             RCDINIT3_FREQ3                                
#define FREQ3_RCDINIT4                             RCDINIT4_FREQ3                                

