//-----------------------------------------------------------------------------
//
//                 (C) COPYRIGHT 2023 ZHIHE COMPUTING CO.,LTD.
//                             ALL RIGHTS RESERVED
//
//  This software and the associated documentation are confidential and
//  proprietary to ZHIHE Computing Co.,Ltd.  Your use or disclosure of
//  this software is subject to the terms and conditions of a written license
//  agreement between you, or your company, and ZHIHE Computing Co.,Ltd
//
//  The entire notice above must be reproduced on all authorized copies.
//
//-----------------------------------------------------------------------------
//  File Name: CPU_SS_C908_CPU_CLK_CCU.h
//  This file is generated by PTC

#ifndef __AP_MAP_CPU_SS_C908_CPU_CLK_CCU_OFFSET_H__
#define __AP_MAP_CPU_SS_C908_CPU_CLK_CCU_OFFSET_H__

#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_TIME 0x10140a00
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_CTRL 0x10140a04
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_STS 0x10140a08
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_CLR 0x10140a0c
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_LP_CTRL 0x10140a10
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_RATIO_LP 0x10140a18
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_RATIO_NORMAL 0x10140a1c
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_INT_STS 0x10140a20
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_INT_CLR 0x10140a24
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_INT_EN 0x10140a28

#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_TIME_DFT_VAL 524608
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_CTRL_DFT_VAL 1
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_STS_DFT_VAL 0
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_CLR_DFT_VAL 0
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_LP_CTRL_DFT_VAL 3
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_RATIO_LP_DFT_VAL 0
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_RATIO_NORMAL_DFT_VAL 0
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_INT_STS_DFT_VAL 0
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_INT_CLR_DFT_VAL 0
#define AP_CPU_SS_C908_CPU_CLK_CCU_CCU_INT_EN_DFT_VAL 0

#endif

