//-----------------------------------------------------------------------------
//
//                 (C) COPYRIGHT 2023 ZHIHE COMPUTING CO.,LTD.
//                             ALL RIGHTS RESERVED
//
//  This software and the associated documentation are confidential and
//  proprietary to ZHIHE Computing Co.,Ltd.  Your use or disclosure of
//  this software is subject to the terms and conditions of a written license
//  agreement between you, or your company, and ZHIHE Computing Co.,Ltd
//
//  The entire notice above must be reproduced on all authorized copies.
//
//-----------------------------------------------------------------------------
//  File Name: CPU_SS_CLK_SYSREG.h
//  This file is generated by PTC

#ifndef __AP_MAP_CPU_SS_CLK_SYSREG_OFFSET_H__
#define __AP_MAP_CPU_SS_CLK_SYSREG_OFFSET_H__

#define AP_CPU_SS_CLK_SYSREG_C908_CLK_CTRL 0x10141600
#define AP_CPU_SS_CLK_SYSREG_C920_CLK_CTRL 0x10141604
#define AP_CPU_SS_CLK_SYSREG_DEBUG_CGEN_INFO 0x10141608
#define AP_CPU_SS_CLK_SYSREG_CPU_SS_CLKGEN_LOCK_0_TEE 0x10141680

#define AP_CPU_SS_CLK_SYSREG_C908_CLK_CTRL_DFT_VAL 0
#define AP_CPU_SS_CLK_SYSREG_C920_CLK_CTRL_DFT_VAL 0
#define AP_CPU_SS_CLK_SYSREG_DEBUG_CGEN_INFO_DFT_VAL 0
#define AP_CPU_SS_CLK_SYSREG_CPU_SS_CLKGEN_LOCK_0_TEE_DFT_VAL 0

#endif

