//-----------------------------------------------------------------------------
//
//                 (C) COPYRIGHT 2023 ZHIHE COMPUTING CO.,LTD.
//                             ALL RIGHTS RESERVED
//
//  This software and the associated documentation are confidential and
//  proprietary to ZHIHE Computing Co.,Ltd.  Your use or disclosure of
//  this software is subject to the terms and conditions of a written license
//  agreement between you, or your company, and ZHIHE Computing Co.,Ltd
//
//  The entire notice above must be reproduced on all authorized copies.
//
//-----------------------------------------------------------------------------
//  File Name: CPU_SS_CPU_PLL.h
//  This file is generated by PTC

#ifndef __AP_MAP_CPU_SS_CPU_PLL_OFFSET_H__
#define __AP_MAP_CPU_SS_CPU_PLL_OFFSET_H__

#define AP_CPU_SS_CPU_PLL_C908_PLL_CFG0 0x10141400
#define AP_CPU_SS_CPU_PLL_C908_PLL_CFG1 0x10141404
#define AP_CPU_SS_CPU_PLL_C908_PLL_CFG2 0x10141408
#define AP_CPU_SS_CPU_PLL_C908_PLL_CFG3 0x1014140c
#define AP_CPU_SS_CPU_PLL_C908_PLL_STS 0x10141410
#define AP_CPU_SS_CPU_PLL_C908_PLL_MON_STS 0x10141414
#define AP_CPU_SS_CPU_PLL_C908_PLL_MON_CFG 0x10141418
#define AP_CPU_SS_CPU_PLL_C920_PLL_CFG0 0x10141440
#define AP_CPU_SS_CPU_PLL_C920_PLL_CFG1 0x10141444
#define AP_CPU_SS_CPU_PLL_C920_PLL_CFG2 0x10141448
#define AP_CPU_SS_CPU_PLL_C920_PLL_CFG3 0x1014144c
#define AP_CPU_SS_CPU_PLL_C920_PLL_STS 0x10141450
#define AP_CPU_SS_CPU_PLL_C920_PLL_MON_STS 0x10141454
#define AP_CPU_SS_CPU_PLL_C920_PLL_MON_CFG 0x10141458
#define AP_CPU_SS_CPU_PLL_TEE_LOCK 0x10141460

#define AP_CPU_SS_CPU_PLL_C908_PLL_CFG0_DFT_VAL 18887169
#define AP_CPU_SS_CPU_PLL_C908_PLL_CFG1_DFT_VAL 50331648
#define AP_CPU_SS_CPU_PLL_C908_PLL_CFG2_DFT_VAL 33554432
#define AP_CPU_SS_CPU_PLL_C908_PLL_CFG3_DFT_VAL 134214656
#define AP_CPU_SS_CPU_PLL_C908_PLL_STS_DFT_VAL 0
#define AP_CPU_SS_CPU_PLL_C908_PLL_MON_STS_DFT_VAL 0
#define AP_CPU_SS_CPU_PLL_C908_PLL_MON_CFG_DFT_VAL 0
#define AP_CPU_SS_CPU_PLL_C920_PLL_CFG0_DFT_VAL 19944705
#define AP_CPU_SS_CPU_PLL_C920_PLL_CFG1_DFT_VAL 50331648
#define AP_CPU_SS_CPU_PLL_C920_PLL_CFG2_DFT_VAL 33554432
#define AP_CPU_SS_CPU_PLL_C920_PLL_CFG3_DFT_VAL 134214656
#define AP_CPU_SS_CPU_PLL_C920_PLL_STS_DFT_VAL 0
#define AP_CPU_SS_CPU_PLL_C920_PLL_MON_STS_DFT_VAL 0
#define AP_CPU_SS_CPU_PLL_C920_PLL_MON_CFG_DFT_VAL 0
#define AP_CPU_SS_CPU_PLL_TEE_LOCK_DFT_VAL 0

#endif

