//-----------------------------------------------------------------------------
//
//                 (C) COPYRIGHT 2023 ZHIHE COMPUTING CO.,LTD.
//                             ALL RIGHTS RESERVED
//
//  This software and the associated documentation are confidential and
//  proprietary to ZHIHE Computing Co.,Ltd.  Your use or disclosure of
//  this software is subject to the terms and conditions of a written license
//  agreement between you, or your company, and ZHIHE Computing Co.,Ltd
//
//  The entire notice above must be reproduced on all authorized copies.
//
//-----------------------------------------------------------------------------
//  File Name: C908_PPU.h
//  This file is generated by PTC

#ifndef __AP_MAP_C908_PPU_OFFSET_H__
#define __AP_MAP_C908_PPU_OFFSET_H__

#define AP_C908_PPU_PPU_SW_R2P 0x10102200
#define AP_C908_PPU_PPU_SW_REQ 0x10102204
#define AP_C908_PPU_PPU_SW_STATE 0x10102208
#define AP_C908_PPU_PPU_CTRL 0x1010220c
#define AP_C908_PPU_PPU_OVR_TIME 0x10102210
#define AP_C908_PPU_PPU_DLY_TIME_CTRL 0x10102214
#define AP_C908_PPU_PPU_DLY_TIME_0 0x10102218
#define AP_C908_PPU_PPU_DLY_TIME_1 0x1010221c
#define AP_C908_PPU_PPU_DLY_TIME_2 0x10102220
#define AP_C908_PPU_PPU_FORCE_MODE 0x10102224
#define AP_C908_PPU_PPU_INT_EN 0x10102228
#define AP_C908_PPU_PPU_INT_CLR 0x1010222c
#define AP_C908_PPU_PPU_INT_STS 0x10102230
#define AP_C908_PPU_PPU_INT_RAW_STS 0x10102234
#define AP_C908_PPU_PPU_RECOVERY 0x10102238
#define AP_C908_PPU_PPU_DYN_SWITCH_STS 0x1010223c
#define AP_C908_PPU_PPU_PWR_STS 0x10102240

#define AP_C908_PPU_PPU_SW_R2P_DFT_VAL 0
#define AP_C908_PPU_PPU_SW_REQ_DFT_VAL 0
#define AP_C908_PPU_PPU_SW_STATE_DFT_VAL 0
#define AP_C908_PPU_PPU_CTRL_DFT_VAL 131072
#define AP_C908_PPU_PPU_OVR_TIME_DFT_VAL 65920
#define AP_C908_PPU_PPU_DLY_TIME_CTRL_DFT_VAL 273
#define AP_C908_PPU_PPU_DLY_TIME_0_DFT_VAL 64
#define AP_C908_PPU_PPU_DLY_TIME_1_DFT_VAL 64
#define AP_C908_PPU_PPU_DLY_TIME_2_DFT_VAL 64
#define AP_C908_PPU_PPU_FORCE_MODE_DFT_VAL 0
#define AP_C908_PPU_PPU_INT_EN_DFT_VAL 0
#define AP_C908_PPU_PPU_INT_CLR_DFT_VAL 0
#define AP_C908_PPU_PPU_INT_STS_DFT_VAL 0
#define AP_C908_PPU_PPU_INT_RAW_STS_DFT_VAL 0
#define AP_C908_PPU_PPU_RECOVERY_DFT_VAL 0
#define AP_C908_PPU_PPU_DYN_SWITCH_STS_DFT_VAL 0
#define AP_C908_PPU_PPU_PWR_STS_DFT_VAL 0

#endif

