//-----------------------------------------------------------------------------
//
//                 (C) COPYRIGHT 2023 ZHIHE COMPUTING CO.,LTD.
//                             ALL RIGHTS RESERVED
//
//  This software and the associated documentation are confidential and
//  proprietary to ZHIHE Computing Co.,Ltd.  Your use or disclosure of
//  this software is subject to the terms and conditions of a written license
//  agreement between you, or your company, and ZHIHE Computing Co.,Ltd
//
//  The entire notice above must be reproduced on all authorized copies.
//
//-----------------------------------------------------------------------------
//  File Name: CPU_SS_TOP_PPU.h
//  This file is generated by PTC

#ifndef __AP_MAP_CPU_SS_TOP_PPU_OFFSET_H__
#define __AP_MAP_CPU_SS_TOP_PPU_OFFSET_H__

#define AP_CPU_SS_TOP_PPU_PPU_SW_R2P 0x10200000
#define AP_CPU_SS_TOP_PPU_PPU_SW_REQ 0x10200004
#define AP_CPU_SS_TOP_PPU_PPU_SW_STATE 0x10200008
#define AP_CPU_SS_TOP_PPU_PPU_CTRL 0x1020000c
#define AP_CPU_SS_TOP_PPU_PPU_OVR_TIME 0x10200010
#define AP_CPU_SS_TOP_PPU_PPU_DLY_TIME_CTRL 0x10200014
#define AP_CPU_SS_TOP_PPU_PPU_DLY_TIME_0 0x10200018
#define AP_CPU_SS_TOP_PPU_PPU_DLY_TIME_1 0x1020001c
#define AP_CPU_SS_TOP_PPU_PPU_DLY_TIME_2 0x10200020
#define AP_CPU_SS_TOP_PPU_PPU_FORCE_MODE 0x10200024
#define AP_CPU_SS_TOP_PPU_PPU_INT_EN 0x10200028
#define AP_CPU_SS_TOP_PPU_PPU_INT_CLR 0x1020002c
#define AP_CPU_SS_TOP_PPU_PPU_INT_STS 0x10200030
#define AP_CPU_SS_TOP_PPU_PPU_INT_RAW_STS 0x10200034
#define AP_CPU_SS_TOP_PPU_PPU_RECOVERY 0x10200038
#define AP_CPU_SS_TOP_PPU_PPU_DYN_SWITCH_STS 0x1020003c
#define AP_CPU_SS_TOP_PPU_PPU_PWR_STS 0x10200040

#define AP_CPU_SS_TOP_PPU_PPU_SW_R2P_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_SW_REQ_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_SW_STATE_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_CTRL_DFT_VAL 131072
#define AP_CPU_SS_TOP_PPU_PPU_OVR_TIME_DFT_VAL 65920
#define AP_CPU_SS_TOP_PPU_PPU_DLY_TIME_CTRL_DFT_VAL 273
#define AP_CPU_SS_TOP_PPU_PPU_DLY_TIME_0_DFT_VAL 64
#define AP_CPU_SS_TOP_PPU_PPU_DLY_TIME_1_DFT_VAL 64
#define AP_CPU_SS_TOP_PPU_PPU_DLY_TIME_2_DFT_VAL 64
#define AP_CPU_SS_TOP_PPU_PPU_FORCE_MODE_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_INT_EN_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_INT_CLR_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_INT_STS_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_INT_RAW_STS_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_RECOVERY_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_DYN_SWITCH_STS_DFT_VAL 0
#define AP_CPU_SS_TOP_PPU_PPU_PWR_STS_DFT_VAL 0

#endif

