//-----------------------------------------------------------------------------
//
//                 (C) COPYRIGHT 2023 ZHIHE COMPUTING CO.,LTD.
//                             ALL RIGHTS RESERVED
//
//  This software and the associated documentation are confidential and
//  proprietary to ZHIHE Computing Co.,Ltd.  Your use or disclosure of
//  this software is subject to the terms and conditions of a written license
//  agreement between you, or your company, and ZHIHE Computing Co.,Ltd
//
//  The entire notice above must be reproduced on all authorized copies.
//
//-----------------------------------------------------------------------------
//  File Name: C908_BPC.h
//  This file is generated by PTC

#ifndef __AP_MAP_C908_BPC_OFFSET_H__
#define __AP_MAP_C908_BPC_OFFSET_H__

#define AP_C908_BPC_BPC_SW_CTR 0x10100e00
#define AP_C908_BPC_BPC_SW_SLEEP_USER 0x10100e04
#define AP_C908_BPC_BPC_SW_ACK 0x10100e08
#define AP_C908_BPC_BPC_SW_RECOVERY_ON 0x10100e0c
#define AP_C908_BPC_BPC_SW_RECOVERY_OFF 0x10100e10
#define AP_C908_BPC_BPC_SW_DELAY 0x10100e14
#define AP_C908_BPC_BPC_SW_USER_DELAY 0x10100e18
#define AP_C908_BPC_BPC_SW_CFG_PM_0_0 0x10100e1c
#define AP_C908_BPC_BPC_SW_CFG_PM_0_1 0x10100e20
#define AP_C908_BPC_BPC_SW_CFG_PM_0_2 0x10100e24
#define AP_C908_BPC_BPC_SW_CFG_PM_1_0 0x10100e2c
#define AP_C908_BPC_BPC_SW_CFG_PM_1_1 0x10100e30
#define AP_C908_BPC_BPC_SW_CFG_PM_1_2 0x10100e34
#define AP_C908_BPC_BPC_SW_CFG_PM_1_3 0x10100e38
#define AP_C908_BPC_BPC_SW_CFG_PM_2 0x10100e3c
#define AP_C908_BPC_BPC_SW_CFG_PM_3 0x10100e4c
#define AP_C908_BPC_BPC_SW_CFG_PM_4 0x10100e5c
#define AP_C908_BPC_BPC_SW_CFG_PM_5 0x10100e6c
#define AP_C908_BPC_BPC_SW_CFG_PM_6 0x10100e7c
#define AP_C908_BPC_BPC_SW_CFG_PM_7 0x10100e8c
#define AP_C908_BPC_BPC_SW_CFG_PM_8 0x10100e9c
#define AP_C908_BPC_BPC_SW_CFG_PM_9 0x10100f0c
#define AP_C908_BPC_BPC_SW_CFG_PM_10 0x10100f1c
#define AP_C908_BPC_BPC_SW_CFG_PM_11 0x10100f2c
#define AP_C908_BPC_BPC_SW_CTR_OPT 0x10100f3c
#define AP_C908_BPC_BPC_CUR_STATE 0x10100f40

#define AP_C908_BPC_BPC_SW_CTR_DFT_VAL 1
#define AP_C908_BPC_BPC_SW_SLEEP_USER_DFT_VAL 257
#define AP_C908_BPC_BPC_SW_ACK_DFT_VAL 0
#define AP_C908_BPC_BPC_SW_RECOVERY_ON_DFT_VAL 0
#define AP_C908_BPC_BPC_SW_RECOVERY_OFF_DFT_VAL 0
#define AP_C908_BPC_BPC_SW_DELAY_DFT_VAL 1145311296
#define AP_C908_BPC_BPC_SW_USER_DELAY_DFT_VAL 0
#define AP_C908_BPC_BPC_SW_CFG_PM_0_0_DFT_VAL 134879003
#define AP_C908_BPC_BPC_SW_CFG_PM_0_1_DFT_VAL 102107907
#define AP_C908_BPC_BPC_SW_CFG_PM_0_2_DFT_VAL 532
#define AP_C908_BPC_BPC_SW_CFG_PM_1_0_DFT_VAL 85262611
#define AP_C908_BPC_BPC_SW_CFG_PM_1_1_DFT_VAL 117704972
#define AP_C908_BPC_BPC_SW_CFG_PM_1_2_DFT_VAL 6172
#define AP_C908_BPC_BPC_SW_CFG_PM_1_3_DFT_VAL 0
#define AP_C908_BPC_BPC_SW_CFG_PM_2_DFT_VAL 7
#define AP_C908_BPC_BPC_SW_CFG_PM_3_DFT_VAL 8
#define AP_C908_BPC_BPC_SW_CFG_PM_4_DFT_VAL 14
#define AP_C908_BPC_BPC_SW_CFG_PM_5_DFT_VAL 16
#define AP_C908_BPC_BPC_SW_CFG_PM_6_DFT_VAL 12
#define AP_C908_BPC_BPC_SW_CFG_PM_7_DFT_VAL 0
#define AP_C908_BPC_BPC_SW_CFG_PM_8_DFT_VAL 13
#define AP_C908_BPC_BPC_SW_CFG_PM_9_DFT_VAL 15
#define AP_C908_BPC_BPC_SW_CFG_PM_10_DFT_VAL 11
#define AP_C908_BPC_BPC_SW_CFG_PM_11_DFT_VAL 0
#define AP_C908_BPC_BPC_SW_CTR_OPT_DFT_VAL 24
#define AP_C908_BPC_BPC_CUR_STATE_DFT_VAL 0

#endif

