//-----------------------------------------------------------------------------
//
//                 (C) COPYRIGHT 2023 ZHIHE COMPUTING CO.,LTD.
//                             ALL RIGHTS RESERVED
//
//  This software and the associated documentation are confidential and
//  proprietary to ZHIHE Computing Co.,Ltd.  Your use or disclosure of
//  this software is subject to the terms and conditions of a written license
//  agreement between you, or your company, and ZHIHE Computing Co.,Ltd
//
//  The entire notice above must be reproduced on all authorized copies.
//
//-----------------------------------------------------------------------------
//  File Name: CPU_SS_COM_APB_CLK_CCU.h
//  This file is generated by PTC

#ifndef __AP_MAP_CPU_SS_COM_APB_CLK_CCU_OFFSET_H__
#define __AP_MAP_CPU_SS_COM_APB_CLK_CCU_OFFSET_H__

#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_TIME 0x10140200
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_CTRL 0x10140204
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_STS 0x10140208
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_CLR 0x1014020c
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_LP_CTRL 0x10140210
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_RATIO_LP 0x10140218
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_RATIO_NORMAL 0x1014021c
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_INT_STS 0x10140220
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_INT_CLR 0x10140224
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_INT_EN 0x10140228

#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_TIME_DFT_VAL 524608
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_CTRL_DFT_VAL 1
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_STS_DFT_VAL 0
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_CLR_DFT_VAL 0
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_LP_CTRL_DFT_VAL 3
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_RATIO_LP_DFT_VAL 0
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_RATIO_NORMAL_DFT_VAL 0
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_INT_STS_DFT_VAL 0
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_INT_CLR_DFT_VAL 0
#define AP_CPU_SS_COM_APB_CLK_CCU_CCU_INT_EN_DFT_VAL 0

#endif

