//-----------------------------------------------------------------------------
//
//                 (C) COPYRIGHT 2023 ZHIHE COMPUTING CO.,LTD.
//                             ALL RIGHTS RESERVED
//
//  This software and the associated documentation are confidential and
//  proprietary to ZHIHE Computing Co.,Ltd.  Your use or disclosure of
//  this software is subject to the terms and conditions of a written license
//  agreement between you, or your company, and ZHIHE Computing Co.,Ltd
//
//  The entire notice above must be reproduced on all authorized copies.
//
//-----------------------------------------------------------------------------
//  File Name: C908_PCTRL_SYSREG.h
//  This file is generated by PTC

#ifndef __AP_MAP_C908_PCTRL_SYSREG_OFFSET_H__
#define __AP_MAP_C908_PCTRL_SYSREG_OFFSET_H__

#define AP_C908_PCTRL_SYSREG_PCTRL_MODE 0x10102800
#define AP_C908_PCTRL_SYSREG_PCTRL_CTRL 0x10102804
#define AP_C908_PCTRL_SYSREG_PCTRL_L2_CACHE_STS 0x10102810
#define AP_C908_PCTRL_SYSREG_PCTRL_SYSREG_LOCK_0_TEE 0x101028fc

#define AP_C908_PCTRL_SYSREG_PCTRL_MODE_DFT_VAL 0
#define AP_C908_PCTRL_SYSREG_PCTRL_CTRL_DFT_VAL 0
#define AP_C908_PCTRL_SYSREG_PCTRL_L2_CACHE_STS_DFT_VAL 0
#define AP_C908_PCTRL_SYSREG_PCTRL_SYSREG_LOCK_0_TEE_DFT_VAL 0

#endif

